apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: node-app
type: Opaque
stringData:
  # Example secret values
  DATABASE_URL: "postgres://user:pass@db:5432/app"
  SECRET_KEY: "supersecretkey"
